import img1 from "../assets/Reguler.svg";
import img2 from "../assets/Medium.svg";
import img3 from "../assets/Premium.svg";

const dataTransaction = [
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
  {
    id: 1,
    package: "Premium",
    price: 1500000,
    image: img3,
    duration: "12 month",
    orderAt: Date.now(),
  },
  {
    id: 2,
    package: "Reguler",
    price: 150000,
    image: img1,
    duration: "1 month",
    orderAt: Date.now(),
  },
  {
    id: 3,
    package: "Medium",
    price: 700000,
    image: img2,
    duration: "6 month",
    orderAt: Date.now(),
  },
];

export default dataTransaction;
